# List of DNA sequences
dna_sequences = [
    "TCGTAACGTAATGGAACCGTTCGCGGCGTCGCGTACATCCAAAAAA",
    "TCGTAACGTGATGGATCCCTTTGCGGCGTCCAAGACTACCAAGAAA",
    "TCGTAACACTATGGAACCATTCGCGGCATCTTCGACTACGAAGCCG",
    "TCGTAATGTTATGGAACCGTTTGCAGCTAGTAAGACTACTAAAAAG",
    "TCGTAACACTATGGAACCTTTTGCATCTAGTAAGACCACAAAAAAA",
    "TCGTAACACTATGGAACCCTTCGCCGCATCCAAAACCTCCAAAAAA",
    "TCGTAATGTGATGGAGCCTTTTGCTTCGTCAACGACCTCGAAACCA",
    "TCGTAATGTAATGGAGCCGTTCGCTGCTAGTAAGACCACGAAAAAG",
    "TCGTAATACCATGGAACCCTTCGCGGCCTCAACAACAACTAAAAAA",
    "TCGTAATGTAATGGAACCCTTTGCTTCAAGCAAGACTTCCAAGAAG",
    "TCGTAACGTAATGGAGCCCTTTGCTTCGTCAACTACGACGAAAAAA",
    "TCGTAACGTAATGGAGCCGTTCGCCTCATCAACCACTAGCAAGAAG",
    "TCGTAATGTCATGGAACCTTTCGCGGCATCGACAACCACGAAACCA",
    "TCGTAACGTCATGGAACCGTTTGCAGCATCAAAGACTACGAAACCG",
    "TCGTAACGTCATGGAGCCCTTCGCTGCAAGTAAGACGTCCAAGAAA",
    "TCGTAACACAATGGAGCCCTTTGCGGCGTCAACGACGTCCAAGAAG",
    "TCGTAATGTTATGGAGCCGTTCGCTTCTTCCAAGACTTCCAAGAAA",
    "TCGTAACGTGATGGAACCATTTGCTGCTAGTACCACGTCTAAGCCT",
    "TCGTAATACTATGGAACCCTTTGCATCGTCTACCACTTCGAAAAAG",
    "TCGTAACACTATGGAGCCCTTTGCGGCGTCAAAAACCACGAAGAAG",
]

# Open a new file to write the commands
with open('S2.sh', 'w') as file:
    for sequence in dna_sequences:
        # Write the grep command for each sequence to the file
        file.write(f'grep -c {sequence} S2.fastq >> S2.txt\n')

# Make the Output.sh file executable
import os
os.chmod('S2.sh', 0o755)

print("S2.sh file has been created with the grep commands.")