fwd_index='';
rev_index='';
target_seq='ATTACTGTAAATGAAAAAGAACACATTCTTGAACAGAAATATCGTCCATCTACTATCGATGAATGTATTCTTCCCGCTTTTGATAAAGAAACCTTTAAATCTATTACAAGTAAAGGTAAGATTCCACATATTATTCTTCATTCTCCTTCTCCAGGAACAGGTAAAACAACTGTAGCAAAAGCATTATGTCATGATGTAAATGCTGATATGATGTTTGTGAATGGGTCAGATTGTAAAATTGATTTCGTTCGTGGTCCTTTGACTAATTTTGCCAGCGCCGCTTCATTTGATGGTCGTCAAAAAGTAATCGTTATTGATGAATTTGACCGTTCAGGGTTAGCAGAGTCTCAGCGACATCTTCGTTCCTTTATG';
counts=zeros(32, numel(target_seq)/3);
cod=['AAG';'CGC';'CGG';'AGG';'GAG';'GAC';'AAC';'CAG';'CAC';'ACC';'ACG';'AGC';'TCC';'TCG';'TGC';'GCC';'GCG';'GTC';'GTG';'CTC';'CTG';'TTG';'ATC';'ATG';'TTC';'TAC';'TGG';'GGC';'GGG';'CCC';'CCG';'TAG']; fclose all;
fid=fopen('C:\Users\sidni\Documents\Pool1.fasta','w');
for i=1:3:numel(target_seq)
    tmp=target_seq;
    for j=1:32
        tmp(i:i+2)=cod(j,:);
        fprintf(fid,'%s\n', (tmp));
    end
    disp(num2str(i));
end
fclose(fid);
